name: Generate Snake

on:
  schedule:
    # Her 6 saatte bir çalışır
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # Repo'yu checkout et
      - uses: actions/checkout@v2

      # Snake GIF oluştur
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: islamVargun
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Çıktı dosyalarını GitHub Pages'e push et
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist

