name: Generate Snake

on:
  schedule:
    # her 6 saatte bir çalışır
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # Repo'yu kontrol et
      - uses: actions/checkout@v2

      # Çıktı dizinini oluştur
      - name: Create Output Directory
        run: mkdir -p dist

      # Snake GIF oluştur
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: islamVargun
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Build durumunu kontrol et
      - run: git status

      # Değişiklikleri push et
      - name: Push changes
        uses: ad-m/github-push-action@v0.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # GitHub Pages'e deploy et
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
